/*
 * Globalize Cultures
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */
import { locales } from "./powerbiGlobalizeLocales";

export default function injectCultures(Globalize) {
    Object.keys(locales).forEach(locale => Globalize.addCultureInfo(locales[locale]));
}